name: demo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version
# 1.1.6+7 Release
version: 1.1.6+7

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  splash_view: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  url_launcher: ^6.0.9
  awesome_dialog: 2.2.1
  flutter_inappwebview: ^5.7.2+3
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  android_intent_plus: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  min_sdk_android: 19

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: my_font
      fonts:
        - asset: assets/fonts/IBMPlexSansKR-Regular.ttf
